const outreachModules = {
  it: [
    ['Antibiotici e antimicrobici','Termini corretti, differenze e perché AMR è più ampia dell’antibiotico-resistenza.','Distinguere antimicrobici, antibiotici e resistenza, senza semplificazioni fuorvianti.',['Definizioni essenziali e campo di applicazione.','Perché gli antibiotici agiscono sui batteri, non su tutti i microrganismi.','Il linguaggio corretto per leggere dati e notizie.'],[['WHO · AMR', 'https://www.who.int/health-topics/antimicrobial-resistance']]],
    ['Batteri, virus e uso appropriato','Quando gli antibiotici non funzionano e perché l’uso appropriato protegge l’efficacia delle terapie.','Spiegare perché una terapia antibiotica richiede diagnosi e prescrizione.',['Batteri e virus: differenze rilevanti per le cure.','Cosa significa uso appropriato.','Perché non conservare o condividere antibiotici.'],[['WHO · Antibiotic resistance', 'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance']]],
    ['Come nasce l’AMR','Selezione, trasmissione, geni e limiti delle metafore semplicistiche.','Descrivere i meccanismi senza suggerire che le persone “diventino resistenti”.',['Variabilità e selezione nelle popolazioni microbiche.','Geni, plasmidi e trasferimento: cosa sappiamo.','Perché la trasmissione dipende dai contesti.'],[['WHO · AMR', 'https://www.who.int/health-topics/antimicrobial-resistance']]],
    ['Giuseppe Brotzu e le cefalosporine','Una storia sarda delle cefalosporine, separando patrimonio storico e messaggi sanitari contemporanei.','Contestualizzare un contributo storico senza trasformarlo in una promessa terapeutica.',['Il contesto scientifico della scoperta.','Dalla ricerca alle cefalosporine: un percorso lungo.','Perché la storia non sostituisce stewardship e sorveglianza.'],[['Treccani · Giuseppe Brotzu', 'https://www.treccani.it/enciclopedia/giuseppe-brotzu/']]],
    ['One Health','Persone, animali, alimenti e ambiente sono connessi, ma i collegamenti causali devono essere dimostrati.','Capire l’approccio One Health e i suoi limiti interpretativi.',['Quattro ambiti, un linguaggio comune.','Dati diversi non sono automaticamente confrontabili.','Come riconoscere un’inferenza non dimostrata.'],[['WHO · One Health', 'https://www.who.int/health-topics/one-health']]],
    ['AMR nelle strutture sanitarie','Che cosa misurano sorveglianza, antibiogrammi e indicatori di copertura.','Leggere le evidenze cliniche senza confondere casi, isolati e prevalenza.',['Dal campione all’antibiogramma.','Sorveglianza: denominatori e copertura.','Cosa può e non può indicare una mappa.'],[['ISS · AR-ISS', 'https://www.epicentro.iss.it/antibiotico-resistenza/ar-iss-rapporto']]],
    ['Filiera alimentare e animali','Come leggere dati veterinari e perché una coorte non equivale a una prevalenza regionale.','Interpretare correttamente i risultati di filiera e sanità animale.',['Campionamento, specie e matrice.','Fenotipo, gene e contesto produttivo.','Perché non localizzare allevamenti o aziende.'],[['EFSA · AMR dashboard', 'https://www.efsa.europa.eu/en/microstrategy/dashboard-antimicrobial-resistance']]],
    ['Acque reflue e resistoma','Che cosa è misurabile, quali sono i limiti e come evitare inferenze improprie.','Comprendere il valore della sorveglianza ambientale senza attribuire rischio individuale.',['Che cos’è un resistoma e come si misura.','Campione, impianto, territorio: scale diverse.','Risultati utili e limiti da dichiarare.'],[['WHO · AMR and environment', 'https://www.who.int/teams/environment-climate-change-and-health/chemical-safety-and-health/antimicrobial-resistance']]],
    ['Depuratori e corsi d’acqua','Recapito autorizzato, prossimità geografica e modello idrologico sono tre concetti distinti.','Separare chiaramente dato amministrativo, osservazione e modello.',['Il punto dell’impianto non è il punto di scarico.','La vicinanza a un fiume non prova il recapito.','Quali evidenze servono per una conclusione responsabile.'],[['Metodo dell’Atlante', 'methodology.html']]],
    ['AR-ISS, EARS-Net e GLASS','I sistemi di sorveglianza hanno obiettivi, scale e denominatori diversi.','Confrontare le piattaforme senza combinare dati incompatibili.',['Che cosa raccoglie AR-ISS.','Il confronto europeo di EARS-Net.','La prospettiva globale di WHO GLASS.'],[['ISS · AR-ISS', 'https://www.epicentro.iss.it/antibiotico-resistenza/ar-iss-rapporto'],['ECDC · EARS-Net', 'https://www.ecdc.europa.eu/en/about-us/partnerships-and-networks/disease-and-laboratory-networks/ears-net'],['WHO · GLASS', 'https://www.who.int/initiatives/glass']]],
    ['Leggere l’Atlante','Filtri, layer, temporalità, schede delle fonti e avvisi di interpretazione.','Usare il cruscotto come strumento di esplorazione delle evidenze, non come diagnosi territoriale.',['Scegliere una classe e un periodo.','Capire layer attivi e risultati non visibili.','Aprire fonti, metodo e limiti prima di confrontare.'],[['Metodo dell’Atlante', 'methodology.html'],['Evidenze e fonti', 'evidence.html']]],
    ['Azioni possibili','Prevenzione, stewardship, igiene, vaccinazioni e uso responsabile delle informazioni.','Tradurre la conoscenza in azioni coerenti con il ruolo di ciascuno.',['Persone: prescrizione, aderenza e prevenzione.','Professionisti e organizzazioni: stewardship e sorveglianza.','Comunicare il rischio senza stigma o allarmismo.'],[['WHO · AWaRe', 'https://www.who.int/teams/integrated-health-services/antimicrobial-resistance/aware']]]
  ],
  en: [
    ['Antibiotics and antimicrobials','Correct terms, key differences and why AMR is broader than antibiotic resistance.','Distinguish antimicrobials, antibiotics and resistance without misleading shortcuts.',['Essential definitions and scope.','Why antibiotics act on bacteria, not every microbe.','Language that helps people read data and news.'],[['WHO · AMR', 'https://www.who.int/health-topics/antimicrobial-resistance']]],
    ['Bacteria, viruses and appropriate use','When antibiotics do not work and why appropriate use protects treatment effectiveness.','Explain why antibiotic therapy needs diagnosis and prescription.',['Bacteria and viruses: differences that matter.','What appropriate use means.','Why antibiotics should not be saved or shared.'],[['WHO · Antibiotic resistance', 'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance']]],
    ['How AMR emerges','Selection, transmission, genes and the limits of simple metaphors.','Describe mechanisms without implying that people become resistant.',['Variation and selection in microbial populations.','Genes, plasmids and transfer: what we know.','Why transmission depends on context.'],[['WHO · AMR', 'https://www.who.int/health-topics/antimicrobial-resistance']]],
    ['Giuseppe Brotzu and cephalosporins','A Sardinian history of cephalosporins, separating historical heritage from current health advice.','Place a historical contribution in context without turning it into a therapeutic promise.',['The scientific setting of the discovery.','From research to cephalosporins: a long route.','Why history does not replace stewardship and surveillance.'],[['Treccani · Giuseppe Brotzu', 'https://www.treccani.it/enciclopedia/giuseppe-brotzu/']]],
    ['One Health','People, animals, food and the environment are connected, but causal links still need evidence.','Understand the One Health approach and its interpretive limits.',['Four domains, a shared language.','Different data are not automatically comparable.','How to spot an unsupported inference.'],[['WHO · One Health', 'https://www.who.int/health-topics/one-health']]],
    ['AMR in healthcare settings','What surveillance, susceptibility testing and coverage indicators measure.','Read clinical evidence without confusing cases, isolates and prevalence.',['From sample to susceptibility test.','Surveillance: denominators and coverage.','What a map can and cannot show.'],[['ISS · AR-ISS', 'https://www.epicentro.iss.it/antibiotico-resistenza/ar-iss-rapporto']]],
    ['Food chain and animals','How to read veterinary data and why a cohort is not regional prevalence.','Interpret food-chain and animal-health findings correctly.',['Sampling, species and matrix.','Phenotype, gene and production context.','Why farms and companies are not mapped.'],[['EFSA · AMR dashboard', 'https://www.efsa.europa.eu/en/microstrategy/dashboard-antimicrobial-resistance']]],
    ['Wastewater and resistome','What can be measured, what remains uncertain and how to avoid improper inference.','Understand the value of environmental surveillance without assigning individual risk.',['What a resistome is and how it is measured.','Sample, facility and territory: different scales.','Useful results and limits that must be stated.'],[['WHO · AMR and environment', 'https://www.who.int/teams/environment-climate-change-and-health/chemical-safety-and-health/antimicrobial-resistance']]],
    ['Treatment plants and rivers','An authorised receiver, geographic proximity and a hydrological model are three distinct concepts.','Keep administrative evidence, observation and modelling clearly separate.',['A facility point is not an outfall point.','Proximity to a river does not prove a receiver.','Evidence needed for a responsible conclusion.'],[['Atlas method', 'methodology.html']]],
    ['AR-ISS, EARS-Net and GLASS','Surveillance systems have different purposes, scales and denominators.','Compare platforms without combining incompatible data.',['What AR-ISS collects.','The European comparison through EARS-Net.','The global perspective of WHO GLASS.'],[['ISS · AR-ISS', 'https://www.epicentro.iss.it/antibiotico-resistenza/ar-iss-rapporto'],['ECDC · EARS-Net', 'https://www.ecdc.europa.eu/en/about-us/partnerships-and-networks/disease-and-laboratory-networks/ears-net'],['WHO · GLASS', 'https://www.who.int/initiatives/glass']]],
    ['Reading the atlas','Filters, layers, time, source records and interpretation warnings.','Use the dashboard to explore evidence, not to diagnose places.',['Choose a class and time period.','Understand active layers and unavailable results.','Open sources, method and limits before comparing.'],[['Atlas method', 'methodology.html'],['Evidence and sources', 'evidence.html']]],
    ['What people can do','Prevention, stewardship, hygiene, vaccination and responsible use of information.','Turn knowledge into actions suitable for each role.',['People: prescription, adherence and prevention.','Professionals and organisations: stewardship and surveillance.','Communicate risk without stigma or alarmism.'],[['WHO · AWaRe', 'https://www.who.int/teams/integrated-health-services/antimicrobial-resistance/aware']]]
  ]
};
const outreachDeckSlugs = ['antibiotici-antimicrobici','batteri-virus-uso-appropriato','come-nasce-amr','brotzu-cefalosporine','one-health','amr-strutture-sanitarie','filiera-alimentare-animali','acque-reflue-resistoma','depuratori-corsi-acqua','ar-iss-ears-net-glass','leggere-atlante','azioni-possibili'];
const assetRoot = document.documentElement.lang === 'en' ? '../' : '';

function renderOutreach() {
  const lang = document.documentElement.lang === 'en' ? 'en' : 'it';
  const data = outreachModules[lang];
  const labels = lang === 'en' ? {progress:'of 12', objective:'Learning objective', scenes:'Narration in three scenes', sources:'Essential sources', deck:'Download PowerPoint presentation', note:'The downloadable presentation includes six slides, source links and speaker notes with video direction.', duration:'3–5 minute narrated presentation'} : {progress:'di 12', objective:'Obiettivo formativo', scenes:'Copione in tre scene', sources:'Fonti essenziali', deck:'Scarica la presentazione PowerPoint', note:'La presentazione scaricabile include sei slide, link alle fonti e note di regia per il video.', duration:'Presentazione narrata di 3–5 minuti'};
  const index = document.getElementById('outreach-index');
  const detail = document.getElementById('outreach-detail');
  let current = 0;
  function show(i) {
    current = i;
    const [title, summary, objective, scenes, sources] = data[i];
    const deckUrl = `${assetRoot}public/outreach/presentations/${String(i + 1).padStart(2, '0')}-${outreachDeckSlugs[i]}-video-slide.pptx`;
    index.innerHTML = data.map((item, n) => `<button type="button" class="outreach-index-row ${n===current?'is-active':''}" data-module="${n}"><strong>${String(n+1).padStart(2,'0')}</strong><span>${item[0]}</span></button>`).join('');
    detail.classList.remove('has-embedded-deck');
    if (lang === 'it' && i === 0) renderEmbeddedModuleOne(detail, deckUrl);
    else detail.innerHTML = `<div class="outreach-progress"><span>${current+1} ${labels.progress}</span><i><b style="width:${((current+1)/12)*100}%"></b></i></div><p class="outreach-number">${lang==='en'?'MODULE':'MODULO'} ${String(current+1).padStart(2,'0')}</p><h2>${title}</h2><p class="outreach-summary">${summary}</p><div class="outreach-detail-grid"><section><h3>${labels.objective}</h3><p>${objective}</p></section><section><h3>${labels.scenes}</h3><ol>${scenes.map(s=>`<li>${s}</li>`).join('')}</ol></section><section><h3>${labels.sources}</h3><ul>${sources.map(([name,url])=>`<li><a href="${url}" ${url.startsWith('http')?'target="_blank" rel="noreferrer"':''}>${name} <span aria-hidden="true">↗</span></a></li>`).join('')}</ul></section></div><p class="outreach-format">${labels.duration}</p><p><a class="inline-action" href="${deckUrl}" download>${labels.deck} <span aria-hidden="true">↓</span></a></p><p class="outreach-note">${labels.note}</p>`;
    index.querySelectorAll('[data-module]').forEach(button => button.addEventListener('click', () => show(Number(button.dataset.module))));
  }
  show(0);
}
document.addEventListener('DOMContentLoaded', renderOutreach);